<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="23" started-at="2019-09-05T08:26:42Z" finished-at="2019-09-05T08:26:42Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="23" started-at="2019-09-05T08:26:42Z" finished-at="2019-09-05T08:26:42Z">
      <class name="hms.intern.SelectionSortTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:hms.intern.SelectionSortTest@17c68925]" name="setUp" is-config="true" duration-ms="5" started-at="2019-09-05T13:56:42Z" finished-at="2019-09-05T13:56:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testSelectionSortNull()[pri:0, instance:hms.intern.SelectionSortTest@17c68925]" name="testSelectionSortNull" duration-ms="4" started-at="2019-09-05T13:56:42Z" finished-at="2019-09-05T13:56:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelectionSortNull -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:hms.intern.SelectionSortTest@17c68925]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-09-05T13:56:42Z" finished-at="2019-09-05T13:56:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:hms.intern.SelectionSortTest@17c68925]" name="setUp" is-config="true" duration-ms="0" started-at="2019-09-05T13:56:42Z" finished-at="2019-09-05T13:56:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testSelectionSorts()[pri:0, instance:hms.intern.SelectionSortTest@17c68925]" name="testSelectionSorts" duration-ms="2" started-at="2019-09-05T13:56:42Z" finished-at="2019-09-05T13:56:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ expected [[I@13a57a3b] but found [[I@7ca48474]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  expected [[I@13a57a3b] but found [[I@7ca48474]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertArrayEquals(Assert.java:144)
	at org.testng.Assert.assertEquals(Assert.java:117)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at hms.intern.SelectionSortTest.testSelectionSorts(SelectionSortTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelectionSorts -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:hms.intern.SelectionSortTest@17c68925]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-09-05T13:56:42Z" finished-at="2019-09-05T13:56:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- hms.intern.SelectionSortTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
